### ISSUE TITLE
Create a custom dataset with augmented images

### ISSUE THREAD

**Issue by MLRadfys** [nadeemlab/Physics-ArX#1]
Hi and thanks for sharing your work!

Iam really interested in creating my own dataset with augmented images using your library. Right now I have about 150 planning CT images and the corresponding CBCT images (taken 1-2 weeks after the pCT).
Unfortunately I wasn't able to figure out how to use the augmentation library or how to get started.

Any advice on that would be highly appreciated! 

Thanks in advance, 

best regards,

Michael

**Comment by sanadeem** [comment]
Thank you for your interest. The pipeline will work best if you have baseline CBCTs (acquired within 1-2 days of planning CT acquisition to ensure no change in tumor or the surrounding anatomy). Assuming you don't have significant morphological change between your planning CT and week 1 CBCT image, you will first (1) run deformable image registration (we used LDDMM) via the ANTs python library (https://stnava.github.io/ANTs/), (2) crop the registered planning CT images to that of the CBCT field-of-view, (3) now you will use the scripts (given in this repository) to (a) extract the scatter artifacts from the registered CBCT images via Adaptive Histogram Equalization, (b) add these artifacts to the registered/cropped planning CT images, (c) perform OS-SART CBCT reconstruction on these artifact-induced planning CTs via the TIGRE library (with parameter variations given in this repository), and finally (d) perform additional geometric augmentations. This should give you the physics-augmented dataset to drive your deep learning pipelines.

Let us know if you need any further information to help you perform physics-based data augmentation on your datasets. In the next few months, we will make it more easier to run all the steps via dockerized containers, pip install, etc. Again thank you for your interest in our work.

**Comment by MLRadfys** [comment]
Thank you very much for the detailed information regarding the use of your augmentation pipeline.

I think I know where to start now :-)

Kind regards,

M
