### ISSUE TITLE
Motion artifact

### ISSUE THREAD

**Issue by Dale-Black** [nadeemlab/Physics-ArX#4]
I am trying to produce realistic simulated CT motion artifacts. From the README, it looks like this code hasn't been completed yet, but the abstract seems to have been published a year ago. Any idea how I can look into this approach more?

**Comment by sanadeem** [comment]
Sorry the student moved to medical physics residency and hence things slowed down a little bit on the next set of artifacts we were planning to add to the Physics-ArX repo. The poster for motion artifact simulation is attached. You will need to have access to 4D CT data from which you will extract projection data every few phases and then combine these to realistically simulate CT motion artifacts. We have another interesting paper coming out hopefully in the next few weeks that will allow realistic simulation of CT motion artifacts without the 4DCT requirement upfront (single 3D CT volume will suffice).

![AAPM2021_CBCT_Motion_Sadegh_Alam](https://user-images.githubusercontent.com/1433402/194971764-aba831bb-7568-4232-ba88-0b3c7168e95a.png)
